### ISSUE TITLE
Rakubrew doesnt work on macOS

### ISSUE THREAD

**Issue by Ovid** [Raku/rakubrew.org#14]
The [rakubrew homespage](https://rakubrew.org/) states:

- Works about anywhere
    - Windows, MacOS, Linux, BSD
    - Powershell, CMD, Bash, Zsh, Fish, ...
- No dependencies except Perl on Unixy machines
- Can get Raku installed and running in seconds
- Autocomplete

It further states that all I need to do is `curl https://rakubrew.org/install-on-macos.sh | sh`.

I'm running macOS Big Sur (Version 11.0.1) and I get this:

```
$ rakubrew download
Couldn't find a precomp release for OS: "macos", architecture: "x86_64"
```

**Comment by patrickbkr** [comment]
That should actually work. I'll look into that. Thanks for the report!

**Comment by lizmat** [comment]
Feels to me this is related to recent changes in the naming of binary packages ?

**Comment by patrickbkr** [comment]
@lizmat I did think about that when introducing the change. So I'm rather confident that's not the reason, but what do I know...

**Comment by patrickbkr** [comment]
@Ovid Can you paste the output of `rakubrew rakubrew-version`? I suspect you are running an older version of rakubrew. (A fix for a similar problem was added in version v12, latest is v14.)

**Comment by Ovid** [comment]
I installed it for the first time today.

```
$ rakubrew rakubrew-version
rakubrew v14 Build type: macos OS: darwin
```

**Comment by patrickbkr** [comment]
I got a fix for this on master. Will be in the next release. If my diagnosis is correct, it should work for you now already since the 2020.12 compiled release files have been uploaded in the meantime. (You managed to hit the time frame where the 2020.12 source release was already published, but the compiled release files weren't.)
Thanks again for the report!
