### ISSUE TITLE
Expired SSL certificate

### ISSUE THREAD

**Issue by sarna** [Raku/rakubrew.org#5]
Hi, your SSL certificate got expired on `12 May 2020` - please renew it, it's hard to manually review a 1.3MB script :)

**Comment by patrickbkr** [comment]
Ping @rba

**Comment by patrickbkr** [comment]
Certificate seems to have been updated. Thanks @rba !

**Comment by rba** [comment]
Hmm. Not yet fine on the server I get connected to. Reopen. I need to look in to this again...

**Comment by davehayes** [comment]
So chromium reports the expired old certificate but cURL reports the new one you renewed on April 12. Firefox gets the new cert as well. I would presume you have browser detection going on because cURL is returning what appears to be ANSI colors in my shell here. You may have to alter your user agent string parsing to pick up chromium at least.

**Comment by nxadm** [comment]
It looks like a Traefik misconfiguration (cert CN is "TRAEFIK DEFAULT CERT").

**Comment by ruivieira** [comment]
> So chromium reports the expired old certificate but cURL reports the new one you renewed on April 12. Firefox gets the new cert as well. I would presume you have browser detection going on because cURL is returning what appears to be ANSI colors in my shell here. You may have to alter your user agent string parsing to pick up chromium at least.

I get an expired certificate with Firefox (expiration date 11 May 2020).

**Comment by rba** [comment]
Certificates updated for now.
